/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.api;

import cn.idmesh.ApiClient;
import cn.idmesh.ApiException;
import cn.idmesh.model.Bucket;
import cn.idmesh.model.KeyValuePair;
import cn.idmesh.model.ModelObject;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.List;

/**
 * API tests for StorageApi
 */
@Disabled
public class StorageApiTest {

    private final ApiClient apiClient = new ApiClient("http://service-gate.api.dev.idmesh.site", "u4X5vTGPH4NCdNTylSYn1JHe", "BkCCUZLVVR9wSi2aiYTOYUZDKps7xgQT");
    private final StorageApi api = new StorageApi(apiClient);

    /**
     * 删除 Bucket
     *
     * 删除bucket会间接删掉bucket下所有object
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteBucketTest() throws ApiException {
        String bucket = null;
        Object response = api.deleteBucket(bucket)
                .execute();
        // TODO: test validations
    }

    /**
     * 删除 Object
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteObjectTest() throws ApiException {
        String bucket = null;
        String key = null;
        String keyAsPrefix = null;
        ModelObject response = api.deleteObject(bucket, key)
                .keyAsPrefix(keyAsPrefix)
                .execute();
        // TODO: test validations
    }

    /**
     * 获取 Bucket 详情
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBucketTest() throws ApiException {
        String bucket = null;
        Bucket response = api.getBucket(bucket)
                .execute();
        // TODO: test validations
    }

    /**
     * 获取 Bucket 列表
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBucketsTest() throws ApiException {
        String last = null;
        Integer limit = null;
        List<Bucket> response = api.getBuckets()
                .last(last)
                .limit(limit)
                .execute();
        // TODO: test validations
    }

    /**
     * 获取 Object 详情
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getObjectTest() throws ApiException {
        String bucket = null;
        String key = null;
        ModelObject response = api.getObject(bucket, key)
                .execute();
        // TODO: test validations
    }

    /**
     * 获取 Object 列表
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getObjectsTest() throws ApiException {
        String bucket = null;
        String last = null;
        Integer limit = null;
        List<ModelObject> response = api.getObjects(bucket)
                .last(last)
                .limit(limit)
                .execute();
        // TODO: test validations
    }

    /**
     * 创建 Object
     *
     * - 如果path中的bucket没有创建，会默认创建 - 如果key已经存在，会更新原有的值 - value 大小最大为 1M 字节 - bucket 最长为 255 个字节
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void saveObjectTest() throws ApiException {
        String bucket = null;
        KeyValuePair keyValuePair = null;
        Object response = api.saveObject(bucket)
                .keyValuePair(keyValuePair)
                .execute();
        // TODO: test validations
    }

}
