/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.idmesh.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IdentityObj
 */
public class IdentityObjTest {
    private final IdentityObj model = new IdentityObj();

    /**
     * Model tests for IdentityObj
     */
    @Test
    public void testIdentityObj() {
        // TODO: test IdentityObj
    }

    /**
     * Test the property 'identityId'
     */
    @Test
    public void identityIdTest() {
        // TODO: test identityId
    }

    /**
     * Test the property 'identityName'
     */
    @Test
    public void identityNameTest() {
        // TODO: test identityName
    }

    /**
     * Test the property 'identityType'
     */
    @Test
    public void identityTypeTest() {
        // TODO: test identityType
    }

}
