/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.idmesh.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IDPConnectionRet
 */
public class IDPConnectionRetTest {
    private final IDPConnectionRet model = new IDPConnectionRet();

    /**
     * Model tests for IDPConnectionRet
     */
    @Test
    public void testIDPConnectionRet() {
        // TODO: test IDPConnectionRet
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'providerId'
     */
    @Test
    public void providerIdTest() {
        // TODO: test providerId
    }

    /**
     * Test the property 'providerCode'
     */
    @Test
    public void providerCodeTest() {
        // TODO: test providerCode
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'configFields'
     */
    @Test
    public void configFieldsTest() {
        // TODO: test configFields
    }

    /**
     * Test the property 'developerId'
     */
    @Test
    public void developerIdTest() {
        // TODO: test developerId
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'logo'
     */
    @Test
    public void logoTest() {
        // TODO: test logo
    }

}
