/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.idmesh.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IDPTestReq
 */
public class IDPTestReqTest {
    private final IDPTestReq model = new IDPTestReq();

    /**
     * Model tests for IDPTestReq
     */
    @Test
    public void testIDPTestReq() {
        // TODO: test IDPTestReq
    }

    /**
     * Test the property 'ldapUrl'
     */
    @Test
    public void ldapUrlTest() {
        // TODO: test ldapUrl
    }

    /**
     * Test the property 'bindDn'
     */
    @Test
    public void bindDnTest() {
        // TODO: test bindDn
    }

    /**
     * Test the property 'bindPassword'
     */
    @Test
    public void bindPasswordTest() {
        // TODO: test bindPassword
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

    /**
     * Test the property 'usersDn'
     */
    @Test
    public void usersDnTest() {
        // TODO: test usersDn
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

}
