/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.idmesh.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ModifyResourceSetMemberReqResourceActionsInner
 */
public class ModifyResourceSetMemberReqResourceActionsInnerTest {
    private final ModifyResourceSetMemberReqResourceActionsInner model = new ModifyResourceSetMemberReqResourceActionsInner();

    /**
     * Model tests for ModifyResourceSetMemberReqResourceActionsInner
     */
    @Test
    public void testModifyResourceSetMemberReqResourceActionsInner() {
        // TODO: test ModifyResourceSetMemberReqResourceActionsInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

}
