/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.idmesh.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.idmesh.model.ResourceSetMemberResourceActions;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResourceSetMember
 */
public class ResourceSetMemberTest {
    private final ResourceSetMember model = new ResourceSetMember();

    /**
     * Model tests for ResourceSetMember
     */
    @Test
    public void testResourceSetMember() {
        // TODO: test ResourceSetMember
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'setId'
     */
    @Test
    public void setIdTest() {
        // TODO: test setId
    }

    /**
     * Test the property 'developerId'
     */
    @Test
    public void developerIdTest() {
        // TODO: test developerId
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'resourceId'
     */
    @Test
    public void resourceIdTest() {
        // TODO: test resourceId
    }

    /**
     * Test the property 'applicationId'
     */
    @Test
    public void applicationIdTest() {
        // TODO: test applicationId
    }

    /**
     * Test the property 'applicationName'
     */
    @Test
    public void applicationNameTest() {
        // TODO: test applicationName
    }

    /**
     * Test the property 'isGlobal'
     */
    @Test
    public void isGlobalTest() {
        // TODO: test isGlobal
    }

    /**
     * Test the property 'resourceType'
     */
    @Test
    public void resourceTypeTest() {
        // TODO: test resourceType
    }

    /**
     * Test the property 'resourceCode'
     */
    @Test
    public void resourceCodeTest() {
        // TODO: test resourceCode
    }

    /**
     * Test the property 'resourceScope'
     */
    @Test
    public void resourceScopeTest() {
        // TODO: test resourceScope
    }

    /**
     * Test the property 'resourceActions'
     */
    @Test
    public void resourceActionsTest() {
        // TODO: test resourceActions
    }

    /**
     * Test the property 'selectedResourceActions'
     */
    @Test
    public void selectedResourceActionsTest() {
        // TODO: test selectedResourceActions
    }

    /**
     * Test the property 'matchAllResourceActions'
     */
    @Test
    public void matchAllResourceActionsTest() {
        // TODO: test matchAllResourceActions
    }

    /**
     * Test the property 'timeModified'
     */
    @Test
    public void timeModifiedTest() {
        // TODO: test timeModified
    }

    /**
     * Test the property 'timeCreated'
     */
    @Test
    public void timeCreatedTest() {
        // TODO: test timeCreated
    }

}
