/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.idmesh.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResourceSet
 */
public class ResourceSetTest {
    private final ResourceSet model = new ResourceSet();

    /**
     * Model tests for ResourceSet
     */
    @Test
    public void testResourceSet() {
        // TODO: test ResourceSet
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'applicationId'
     */
    @Test
    public void applicationIdTest() {
        // TODO: test applicationId
    }

    /**
     * Test the property 'applicationName'
     */
    @Test
    public void applicationNameTest() {
        // TODO: test applicationName
    }

    /**
     * Test the property 'isGlobal'
     */
    @Test
    public void isGlobalTest() {
        // TODO: test isGlobal
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'timeModified'
     */
    @Test
    public void timeModifiedTest() {
        // TODO: test timeModified
    }

    /**
     * Test the property 'timeCreated'
     */
    @Test
    public void timeCreatedTest() {
        // TODO: test timeCreated
    }

}
