/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for AppConfigRet
 */
public class AppConfigRetTest {
    private final AppConfigRet model = new AppConfigRet();

    /**
     * Model tests for AppConfigRet
     */
    @Test
    public void testAppConfigRet() {
        // TODO: test AppConfigRet
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'appId'
     */
    @Test
    public void appIdTest() {
        // TODO: test appId
    }

    /**
     * Test the property 'allowedLoginMethod'
     */
    @Test
    public void allowedLoginMethodTest() {
        // TODO: test allowedLoginMethod
    }

    /**
     * Test the property 'defaultLoginMethod'
     */
    @Test
    public void defaultLoginMethodTest() {
        // TODO: test defaultLoginMethod
    }

    /**
     * Test the property 'allowedRegMethod'
     */
    @Test
    public void allowedRegMethodTest() {
        // TODO: test allowedRegMethod
    }

    /**
     * Test the property 'defaultRegMethod'
     */
    @Test
    public void defaultRegMethodTest() {
        // TODO: test defaultRegMethod
    }

    /**
     * Test the property 'accessPolicy'
     */
    @Test
    public void accessPolicyTest() {
        // TODO: test accessPolicy
    }

    /**
     * Test the property 'regPolicy'
     */
    @Test
    public void regPolicyTest() {
        // TODO: test regPolicy
    }

    /**
     * Test the property 'allowedIdProvider'
     */
    @Test
    public void allowedIdProviderTest() {
        // TODO: test allowedIdProvider
    }

    /**
     * Test the property 'ssoEnabled'
     */
    @Test
    public void ssoEnabledTest() {
        // TODO: test ssoEnabled
    }

    /**
     * Test the property 'mfaEnabled'
     */
    @Test
    public void mfaEnabledTest() {
        // TODO: test mfaEnabled
    }

    /**
     * Test the property 'mfaConfig'
     */
    @Test
    public void mfaConfigTest() {
        // TODO: test mfaConfig
    }

    /**
     * Test the property 'timeCreated'
     */
    @Test
    public void timeCreatedTest() {
        // TODO: test timeCreated
    }

    /**
     * Test the property 'timeModified'
     */
    @Test
    public void timeModifiedTest() {
        // TODO: test timeModified
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
