/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for AppSubAccount
 */
public class AppSubAccountTest {
    private final AppSubAccount model = new AppSubAccount();

    /**
     * Model tests for AppSubAccount
     */
    @Test
    public void testAppSubAccount() {
        // TODO: test AppSubAccount
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'appId'
     */
    @Test
    public void appIdTest() {
        // TODO: test appId
    }

    /**
     * Test the property 'appName'
     */
    @Test
    public void appNameTest() {
        // TODO: test appName
    }

    /**
     * Test the property 'accName'
     */
    @Test
    public void accNameTest() {
        // TODO: test accName
    }

    /**
     * Test the property 'accNameDisplayed'
     */
    @Test
    public void accNameDisplayedTest() {
        // TODO: test accNameDisplayed
    }

    /**
     * Test the property 'accSource'
     */
    @Test
    public void accSourceTest() {
        // TODO: test accSource
    }

    /**
     * Test the property 'developerId'
     */
    @Test
    public void developerIdTest() {
        // TODO: test developerId
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'accPassword'
     */
    @Test
    public void accPasswordTest() {
        // TODO: test accPassword
    }

    /**
     * Test the property 'accStatus'
     */
    @Test
    public void accStatusTest() {
        // TODO: test accStatus
    }

    /**
     * Test the property 'accSyncStatus'
     */
    @Test
    public void accSyncStatusTest() {
        // TODO: test accSyncStatus
    }

    /**
     * Test the property 'sysExtProps'
     */
    @Test
    public void sysExtPropsTest() {
        // TODO: test sysExtProps
    }

    /**
     * Test the property 'freeExtProps'
     */
    @Test
    public void freeExtPropsTest() {
        // TODO: test freeExtProps
    }

    /**
     * Test the property 'timeCreated'
     */
    @Test
    public void timeCreatedTest() {
        // TODO: test timeCreated
    }

    /**
     * Test the property 'timeModified'
     */
    @Test
    public void timeModifiedTest() {
        // TODO: test timeModified
    }

    /**
     * Test the property 'expireAt'
     */
    @Test
    public void expireAtTest() {
        // TODO: test expireAt
    }

}
