/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for App
 */
public class AppTest {
    private final App model = new App();

    /**
     * Model tests for App
     */
    @Test
    public void testApp() {
        // TODO: test App
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'developerId'
     */
    @Test
    public void developerIdTest() {
        // TODO: test developerId
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'appId'
     */
    @Test
    public void appIdTest() {
        // TODO: test appId
    }

    /**
     * Test the property 'templateId'
     */
    @Test
    public void templateIdTest() {
        // TODO: test templateId
    }

    /**
     * Test the property 'templateVersion'
     */
    @Test
    public void templateVersionTest() {
        // TODO: test templateVersion
    }

    /**
     * Test the property 'latestTemplateVersion'
     */
    @Test
    public void latestTemplateVersionTest() {
        // TODO: test latestTemplateVersion
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'appSecret'
     */
    @Test
    public void appSecretTest() {
        // TODO: test appSecret
    }

    /**
     * Test the property 'descr'
     */
    @Test
    public void descrTest() {
        // TODO: test descr
    }

    /**
     * Test the property 'logo'
     */
    @Test
    public void logoTest() {
        // TODO: test logo
    }

    /**
     * Test the property 'loginUrl'
     */
    @Test
    public void loginUrlTest() {
        // TODO: test loginUrl
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'domainSn'
     */
    @Test
    public void domainSnTest() {
        // TODO: test domainSn
    }

    /**
     * Test the property 'redirectUrl'
     */
    @Test
    public void redirectUrlTest() {
        // TODO: test redirectUrl
    }

    /**
     * Test the property 'logoutUrl'
     */
    @Test
    public void logoutUrlTest() {
        // TODO: test logoutUrl
    }

    /**
     * Test the property 'subAccountPolicy'
     */
    @Test
    public void subAccountPolicyTest() {
        // TODO: test subAccountPolicy
    }

    /**
     * Test the property 'sysExtProps'
     */
    @Test
    public void sysExtPropsTest() {
        // TODO: test sysExtProps
    }

    /**
     * Test the property 'freeExtProps'
     */
    @Test
    public void freeExtPropsTest() {
        // TODO: test freeExtProps
    }

    /**
     * Test the property 'timeCreated'
     */
    @Test
    public void timeCreatedTest() {
        // TODO: test timeCreated
    }

    /**
     * Test the property 'timeModified'
     */
    @Test
    public void timeModifiedTest() {
        // TODO: test timeModified
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'config'
     */
    @Test
    public void configTest() {
        // TODO: test config
    }

    /**
     * Test the property 'protocols'
     */
    @Test
    public void protocolsTest() {
        // TODO: test protocols
    }

}
