/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for BatchDeleteUserReq
 */
public class BatchDeleteUserReqTest {
    private final BatchDeleteUserReq model = new BatchDeleteUserReq();

    /**
     * Model tests for BatchDeleteUserReq
     */
    @Test
    public void testBatchDeleteUserReq() {
        // TODO: test BatchDeleteUserReq
    }

    /**
     * Test the property 'ids'
     */
    @Test
    public void idsTest() {
        // TODO: test ids
    }

}
