/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CommonRet
 */
public class CommonRetTest {
    private final CommonRet model = new CommonRet();

    /**
     * Model tests for CommonRet
     */
    @Test
    public void testCommonRet() {
        // TODO: test CommonRet
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
