/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateIDPConnectionReq
 */
public class CreateIDPConnectionReqTest {
    private final CreateIDPConnectionReq model = new CreateIDPConnectionReq();

    /**
     * Model tests for CreateIDPConnectionReq
     */
    @Test
    public void testCreateIDPConnectionReq() {
        // TODO: test CreateIDPConnectionReq
    }

    /**
     * Test the property 'providerCode'
     */
    @Test
    public void providerCodeTest() {
        // TODO: test providerCode
    }

    /**
     * Test the property 'configFields'
     */
    @Test
    public void configFieldsTest() {
        // TODO: test configFields
    }

}
