/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateOrganizationReq
 */
public class CreateOrganizationReqTest {
    private final CreateOrganizationReq model = new CreateOrganizationReq();

    /**
     * Model tests for CreateOrganizationReq
     */
    @Test
    public void testCreateOrganizationReq() {
        // TODO: test CreateOrganizationReq
    }

    /**
     * Test the property 'objectDisplayName'
     */
    @Test
    public void objectDisplayNameTest() {
        // TODO: test objectDisplayName
    }

    /**
     * Test the property 'objectType'
     */
    @Test
    public void objectTypeTest() {
        // TODO: test objectType
    }

    /**
     * Test the property 'objectCode'
     */
    @Test
    public void objectCodeTest() {
        // TODO: test objectCode
    }

    /**
     * Test the property 'objectProps'
     */
    @Test
    public void objectPropsTest() {
        // TODO: test objectProps
    }

    /**
     * Test the property 'isDefault'
     */
    @Test
    public void isDefaultTest() {
        // TODO: test isDefault
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
