/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateAppReqConfigPropAccessPolicy
 */
public class CreateAppReqConfigPropAccessPolicyTest {
    private final CreateAppReqConfigPropAccessPolicy model = new CreateAppReqConfigPropAccessPolicy();

    /**
     * Model tests for CreateAppReqConfigPropAccessPolicy
     */
    @Test
    public void testCreateAppReqConfigPropAccessPolicy() {
        // TODO: test CreateAppReqConfigPropAccessPolicy
    }

    /**
     * Test the property 'forgetPassword'
     */
    @Test
    public void forgetPasswordTest() {
        // TODO: test forgetPassword
    }

}
