/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ModifyAppConfigReq
 */
public class ModifyAppConfigReqTest {
    private final ModifyAppConfigReq model = new ModifyAppConfigReq();

    /**
     * Model tests for ModifyAppConfigReq
     */
    @Test
    public void testModifyAppConfigReq() {
        // TODO: test ModifyAppConfigReq
    }

    /**
     * Test the property 'allowedLoginMethod'
     */
    @Test
    public void allowedLoginMethodTest() {
        // TODO: test allowedLoginMethod
    }

    /**
     * Test the property 'defaultLoginMethod'
     */
    @Test
    public void defaultLoginMethodTest() {
        // TODO: test defaultLoginMethod
    }

    /**
     * Test the property 'allowedRegMethod'
     */
    @Test
    public void allowedRegMethodTest() {
        // TODO: test allowedRegMethod
    }

    /**
     * Test the property 'defaultRegMethod'
     */
    @Test
    public void defaultRegMethodTest() {
        // TODO: test defaultRegMethod
    }

    /**
     * Test the property 'defaultProtocol'
     */
    @Test
    public void defaultProtocolTest() {
        // TODO: test defaultProtocol
    }

    /**
     * Test the property 'accessPolicy'
     */
    @Test
    public void accessPolicyTest() {
        // TODO: test accessPolicy
    }

    /**
     * Test the property 'regPolicy'
     */
    @Test
    public void regPolicyTest() {
        // TODO: test regPolicy
    }

}
