/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ModifyResourceSetReq
 */
public class ModifyResourceSetReqTest {
    private final ModifyResourceSetReq model = new ModifyResourceSetReq();

    /**
     * Model tests for ModifyResourceSetReq
     */
    @Test
    public void testModifyResourceSetReq() {
        // TODO: test ModifyResourceSetReq
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

}
