/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ModifyResourceSetMemberReq
 */
public class ModifyResourceSetMemberReqTest {
    private final ModifyResourceSetMemberReq model = new ModifyResourceSetMemberReq();

    /**
     * Model tests for ModifyResourceSetMemberReq
     */
    @Test
    public void testModifyResourceSetMemberReq() {
        // TODO: test ModifyResourceSetMemberReq
    }

    /**
     * Test the property 'resourceId'
     */
    @Test
    public void resourceIdTest() {
        // TODO: test resourceId
    }

    /**
     * Test the property 'resourceScope'
     */
    @Test
    public void resourceScopeTest() {
        // TODO: test resourceScope
    }

    /**
     * Test the property 'resourceActions'
     */
    @Test
    public void resourceActionsTest() {
        // TODO: test resourceActions
    }

    /**
     * Test the property 'matchAllActions'
     */
    @Test
    public void matchAllActionsTest() {
        // TODO: test matchAllActions
    }

}
