/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ModifyIDPConnectionReqConfigFields
 */
public class ModifyIDPConnectionReqConfigFieldsTest {
    private final ModifyIDPConnectionReqConfigFields model = new ModifyIDPConnectionReqConfigFields();

    /**
     * Model tests for ModifyIDPConnectionReqConfigFields
     */
    @Test
    public void testModifyIDPConnectionReqConfigFields() {
        // TODO: test ModifyIDPConnectionReqConfigFields
    }

    /**
     * Test the property 'corpId'
     */
    @Test
    public void corpIdTest() {
        // TODO: test corpId
    }

    /**
     * Test the property 'agentId'
     */
    @Test
    public void agentIdTest() {
        // TODO: test agentId
    }

    /**
     * Test the property 'corpSecret'
     */
    @Test
    public void corpSecretTest() {
        // TODO: test corpSecret
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

}
