/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for NodeMemberWithPage
 */
public class NodeMemberWithPageTest {
    private final NodeMemberWithPage model = new NodeMemberWithPage();

    /**
     * Model tests for NodeMemberWithPage
     */
    @Test
    public void testNodeMemberWithPage() {
        // TODO: test NodeMemberWithPage
    }

    /**
     * Test the property 'totalNum'
     */
    @Test
    public void totalNumTest() {
        // TODO: test totalNum
    }

    /**
     * Test the property 'currentPage'
     */
    @Test
    public void currentPageTest() {
        // TODO: test currentPage
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
