/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ResetAppProtocolSecretRet
 */
public class ResetAppProtocolSecretRetTest {
    private final ResetAppProtocolSecretRet model = new ResetAppProtocolSecretRet();

    /**
     * Model tests for ResetAppProtocolSecretRet
     */
    @Test
    public void testResetAppProtocolSecretRet() {
        // TODO: test ResetAppProtocolSecretRet
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
