/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;

import cn.idmesh.JSON;

/**
 * AuthConfigRet
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AuthConfigRet {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_AUTH_METHOD_CODE = "auth_method_code";
  @SerializedName(SERIALIZED_NAME_AUTH_METHOD_CODE)
  private String authMethodCode;

  public static final String SERIALIZED_NAME_AUTH_METHOD_DISPLAY_NAME = "auth_method_display_name";
  @SerializedName(SERIALIZED_NAME_AUTH_METHOD_DISPLAY_NAME)
  private String authMethodDisplayName;

  public static final String SERIALIZED_NAME_AUTH_COMP = "auth_comp";
  @SerializedName(SERIALIZED_NAME_AUTH_COMP)
  private String authComp;

  public static final String SERIALIZED_NAME_IDP_CODE = "idp_code";
  @SerializedName(SERIALIZED_NAME_IDP_CODE)
  private String idpCode;

  public static final String SERIALIZED_NAME_IDP_NAME = "idp_name";
  @SerializedName(SERIALIZED_NAME_IDP_NAME)
  private String idpName;

  public static final String SERIALIZED_NAME_IDP_PROVIDER_CHANNEL = "idp_provider_channel";
  @SerializedName(SERIALIZED_NAME_IDP_PROVIDER_CHANNEL)
  private String idpProviderChannel;

  public static final String SERIALIZED_NAME_IDP_TYPE = "idp_type";
  @SerializedName(SERIALIZED_NAME_IDP_TYPE)
  private String idpType;

  public static final String SERIALIZED_NAME_IDP_FEATURE = "idp_feature";
  @SerializedName(SERIALIZED_NAME_IDP_FEATURE)
  private String idpFeature;

  public static final String SERIALIZED_NAME_IDP_LOGO = "idp_logo";
  @SerializedName(SERIALIZED_NAME_IDP_LOGO)
  private String idpLogo;

  public static final String SERIALIZED_NAME_IDP_DESCR = "idp_descr";
  @SerializedName(SERIALIZED_NAME_IDP_DESCR)
  private String idpDescr;

  public static final String SERIALIZED_NAME_IDP_CONFIG_FIELDS = "idp_config_fields";
  @SerializedName(SERIALIZED_NAME_IDP_CONFIG_FIELDS)
  private Object idpConfigFields;

  public static final String SERIALIZED_NAME_IDP_API_NODES = "idp_api_nodes";
  @SerializedName(SERIALIZED_NAME_IDP_API_NODES)
  private String idpApiNodes;

  public static final String SERIALIZED_NAME_IDP_CONFIG_ID = "idp_config_id";
  @SerializedName(SERIALIZED_NAME_IDP_CONFIG_ID)
  private String idpConfigId;

  public static final String SERIALIZED_NAME_IDP_CONFIG_DISPLAY_NAME = "idp_config_display_name";
  @SerializedName(SERIALIZED_NAME_IDP_CONFIG_DISPLAY_NAME)
  private String idpConfigDisplayName;

  public AuthConfigRet() {
  }
   /**
   * 认证方式配置的ID
   * @return id
  **/
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }

   /**
   * 认证方式（AM）的配置代码
   * @return authMethodCode
  **/
  @javax.annotation.Nonnull
  public String getAuthMethodCode() {
    return authMethodCode;
  }


  public void setAuthMethodCode(String authMethodCode) {
    this.authMethodCode = authMethodCode;
  }

   /**
   * 认证方式（AM）的显示名称
   * @return authMethodDisplayName
  **/
  @javax.annotation.Nonnull
  public String getAuthMethodDisplayName() {
    return authMethodDisplayName;
  }


  public void setAuthMethodDisplayName(String authMethodDisplayName) {
    this.authMethodDisplayName = authMethodDisplayName;
  }

   /**
   * 认证方式（AM）的组件代码
   * @return authComp
  **/
  @javax.annotation.Nonnull
  public String getAuthComp() {
    return authComp;
  }


  public void setAuthComp(String authComp) {
    this.authComp = authComp;
  }

   /**
   * 身份源提供者IDP的CODE
   * @return idpCode
  **/
  @javax.annotation.Nonnull
  public String getIdpCode() {
    return idpCode;
  }


  public void setIdpCode(String idpCode) {
    this.idpCode = idpCode;
  }

   /**
   * 身份源提供者IDP的名称
   * @return idpName
  **/
  @javax.annotation.Nonnull
  public String getIdpName() {
    return idpName;
  }


  public void setIdpName(String idpName) {
    this.idpName = idpName;
  }

   /**
   * 身份源提供者IDP的厂商渠道（如钉钉）
   * @return idpProviderChannel
  **/
  @javax.annotation.Nonnull
  public String getIdpProviderChannel() {
    return idpProviderChannel;
  }


  public void setIdpProviderChannel(String idpProviderChannel) {
    this.idpProviderChannel = idpProviderChannel;
  }

   /**
   * 身份源提供者IDP的类型（企业/社会化）
   * @return idpType
  **/
  @javax.annotation.Nonnull
  public String getIdpType() {
    return idpType;
  }


  public void setIdpType(String idpType) {
    this.idpType = idpType;
  }

   /**
   * 身份源提供者IDP的特性（multiple/single）
   * @return idpFeature
  **/
  @javax.annotation.Nonnull
  public String getIdpFeature() {
    return idpFeature;
  }


  public void setIdpFeature(String idpFeature) {
    this.idpFeature = idpFeature;
  }

   /**
   * 身份源提供者IDP的logo
   * @return idpLogo
  **/
  @javax.annotation.Nonnull
  public String getIdpLogo() {
    return idpLogo;
  }


  public void setIdpLogo(String idpLogo) {
    this.idpLogo = idpLogo;
  }

   /**
   * 身份源提供者IDP描述
   * @return idpDescr
  **/
  @javax.annotation.Nonnull
  public String getIdpDescr() {
    return idpDescr;
  }


  public void setIdpDescr(String idpDescr) {
    this.idpDescr = idpDescr;
  }

   /**
   * 身份源提供者IDP配置字段
   * @return idpConfigFields
  **/
  @javax.annotation.Nullable
  public Object getIdpConfigFields() {
    return idpConfigFields;
  }


  public void setIdpConfigFields(Object idpConfigFields) {
    this.idpConfigFields = idpConfigFields;
  }

   /**
   * 身份源提供者IDP的API相关参数
   * @return idpApiNodes
  **/
  @javax.annotation.Nonnull
  public String getIdpApiNodes() {
    return idpApiNodes;
  }


  public void setIdpApiNodes(String idpApiNodes) {
    this.idpApiNodes = idpApiNodes;
  }

   /**
   * 身份源提供者IDP配置项的ID
   * @return idpConfigId
  **/
  @javax.annotation.Nonnull
  public String getIdpConfigId() {
    return idpConfigId;
  }


  public void setIdpConfigId(String idpConfigId) {
    this.idpConfigId = idpConfigId;
  }

   /**
   * 身份源提供者IDP配置显示的名称
   * @return idpConfigDisplayName
  **/
  @javax.annotation.Nonnull
  public String getIdpConfigDisplayName() {
    return idpConfigDisplayName;
  }


  public void setIdpConfigDisplayName(String idpConfigDisplayName) {
    this.idpConfigDisplayName = idpConfigDisplayName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthConfigRet authConfigRet = (AuthConfigRet) o;
    return Objects.equals(this.id, authConfigRet.id) &&
        Objects.equals(this.authMethodCode, authConfigRet.authMethodCode) &&
        Objects.equals(this.authMethodDisplayName, authConfigRet.authMethodDisplayName) &&
        Objects.equals(this.authComp, authConfigRet.authComp) &&
        Objects.equals(this.idpCode, authConfigRet.idpCode) &&
        Objects.equals(this.idpName, authConfigRet.idpName) &&
        Objects.equals(this.idpProviderChannel, authConfigRet.idpProviderChannel) &&
        Objects.equals(this.idpType, authConfigRet.idpType) &&
        Objects.equals(this.idpFeature, authConfigRet.idpFeature) &&
        Objects.equals(this.idpLogo, authConfigRet.idpLogo) &&
        Objects.equals(this.idpDescr, authConfigRet.idpDescr) &&
        Objects.equals(this.idpConfigFields, authConfigRet.idpConfigFields) &&
        Objects.equals(this.idpApiNodes, authConfigRet.idpApiNodes) &&
        Objects.equals(this.idpConfigId, authConfigRet.idpConfigId) &&
        Objects.equals(this.idpConfigDisplayName, authConfigRet.idpConfigDisplayName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, authMethodCode, authMethodDisplayName, authComp, idpCode, idpName, idpProviderChannel, idpType, idpFeature, idpLogo, idpDescr, idpConfigFields, idpApiNodes, idpConfigId, idpConfigDisplayName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthConfigRet {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    authMethodCode: ").append(toIndentedString(authMethodCode)).append("\n");
    sb.append("    authMethodDisplayName: ").append(toIndentedString(authMethodDisplayName)).append("\n");
    sb.append("    authComp: ").append(toIndentedString(authComp)).append("\n");
    sb.append("    idpCode: ").append(toIndentedString(idpCode)).append("\n");
    sb.append("    idpName: ").append(toIndentedString(idpName)).append("\n");
    sb.append("    idpProviderChannel: ").append(toIndentedString(idpProviderChannel)).append("\n");
    sb.append("    idpType: ").append(toIndentedString(idpType)).append("\n");
    sb.append("    idpFeature: ").append(toIndentedString(idpFeature)).append("\n");
    sb.append("    idpLogo: ").append(toIndentedString(idpLogo)).append("\n");
    sb.append("    idpDescr: ").append(toIndentedString(idpDescr)).append("\n");
    sb.append("    idpConfigFields: ").append(toIndentedString(idpConfigFields)).append("\n");
    sb.append("    idpApiNodes: ").append(toIndentedString(idpApiNodes)).append("\n");
    sb.append("    idpConfigId: ").append(toIndentedString(idpConfigId)).append("\n");
    sb.append("    idpConfigDisplayName: ").append(toIndentedString(idpConfigDisplayName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("auth_method_code");
    openapiFields.add("auth_method_display_name");
    openapiFields.add("auth_comp");
    openapiFields.add("idp_code");
    openapiFields.add("idp_name");
    openapiFields.add("idp_provider_channel");
    openapiFields.add("idp_type");
    openapiFields.add("idp_feature");
    openapiFields.add("idp_logo");
    openapiFields.add("idp_descr");
    openapiFields.add("idp_config_fields");
    openapiFields.add("idp_api_nodes");
    openapiFields.add("idp_config_id");
    openapiFields.add("idp_config_display_name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("auth_method_code");
    openapiRequiredFields.add("auth_method_display_name");
    openapiRequiredFields.add("auth_comp");
    openapiRequiredFields.add("idp_code");
    openapiRequiredFields.add("idp_name");
    openapiRequiredFields.add("idp_provider_channel");
    openapiRequiredFields.add("idp_type");
    openapiRequiredFields.add("idp_feature");
    openapiRequiredFields.add("idp_logo");
    openapiRequiredFields.add("idp_descr");
    openapiRequiredFields.add("idp_api_nodes");
    openapiRequiredFields.add("idp_config_id");
    openapiRequiredFields.add("idp_config_display_name");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to AuthConfigRet
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AuthConfigRet.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AuthConfigRet is not found in the empty JSON string", AuthConfigRet.openapiRequiredFields.toString()));
        }
      }


      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AuthConfigRet.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("auth_method_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `auth_method_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("auth_method_code").toString()));
      }
      if (!jsonObj.get("auth_method_display_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `auth_method_display_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("auth_method_display_name").toString()));
      }
      if (!jsonObj.get("auth_comp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `auth_comp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("auth_comp").toString()));
      }
      if (!jsonObj.get("idp_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `idp_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("idp_code").toString()));
      }
      if (!jsonObj.get("idp_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `idp_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("idp_name").toString()));
      }
      if (!jsonObj.get("idp_provider_channel").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `idp_provider_channel` to be a primitive type in the JSON string but got `%s`", jsonObj.get("idp_provider_channel").toString()));
      }
      if (!jsonObj.get("idp_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `idp_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("idp_type").toString()));
      }
      if (!jsonObj.get("idp_feature").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `idp_feature` to be a primitive type in the JSON string but got `%s`", jsonObj.get("idp_feature").toString()));
      }
      if (!jsonObj.get("idp_logo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `idp_logo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("idp_logo").toString()));
      }
      if (!jsonObj.get("idp_descr").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `idp_descr` to be a primitive type in the JSON string but got `%s`", jsonObj.get("idp_descr").toString()));
      }
      if (!jsonObj.get("idp_api_nodes").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `idp_api_nodes` to be a primitive type in the JSON string but got `%s`", jsonObj.get("idp_api_nodes").toString()));
      }
      if (!jsonObj.get("idp_config_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `idp_config_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("idp_config_id").toString()));
      }
      if (!jsonObj.get("idp_config_display_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `idp_config_display_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("idp_config_display_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AuthConfigRet.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AuthConfigRet' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AuthConfigRet> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AuthConfigRet.class));

       return (TypeAdapter<T>) new TypeAdapter<AuthConfigRet>() {
           @Override
           public void write(JsonWriter out, AuthConfigRet value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AuthConfigRet read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AuthConfigRet given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AuthConfigRet
  * @throws IOException if the JSON string is invalid with respect to AuthConfigRet
  */
  public static AuthConfigRet fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AuthConfigRet.class);
  }

 /**
  * Convert an instance of AuthConfigRet to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

