/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;

import cn.idmesh.JSON;

/**
 * BatchCreateAuthUnitRuleReqIdentitiesInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BatchCreateAuthUnitRuleReqIdentitiesInner {
  public static final String SERIALIZED_NAME_IDENTITY_ID = "identity_id";
  @SerializedName(SERIALIZED_NAME_IDENTITY_ID)
  private String identityId;

  public static final String SERIALIZED_NAME_IDENTITY_TYPE = "identity_type";
  @SerializedName(SERIALIZED_NAME_IDENTITY_TYPE)
  private String identityType;

  public BatchCreateAuthUnitRuleReqIdentitiesInner() {
  }
   /**
   * Get identityId
   * @return identityId
  **/
  @javax.annotation.Nonnull
  public String getIdentityId() {
    return identityId;
  }


  public void setIdentityId(String identityId) {
    this.identityId = identityId;
  }

   /**
   * user 用户 ，programmer 编程者，node 组织/自定义关系
   * @return identityType
  **/
  @javax.annotation.Nonnull
  public String getIdentityType() {
    return identityType;
  }


  public void setIdentityType(String identityType) {
    this.identityType = identityType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchCreateAuthUnitRuleReqIdentitiesInner batchCreateAuthUnitRuleReqIdentitiesInner = (BatchCreateAuthUnitRuleReqIdentitiesInner) o;
    return Objects.equals(this.identityId, batchCreateAuthUnitRuleReqIdentitiesInner.identityId) &&
        Objects.equals(this.identityType, batchCreateAuthUnitRuleReqIdentitiesInner.identityType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identityId, identityType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchCreateAuthUnitRuleReqIdentitiesInner {\n");
    sb.append("    identityId: ").append(toIndentedString(identityId)).append("\n");
    sb.append("    identityType: ").append(toIndentedString(identityType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("identity_id");
    openapiFields.add("identity_type");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("identity_id");
    openapiRequiredFields.add("identity_type");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to BatchCreateAuthUnitRuleReqIdentitiesInner
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BatchCreateAuthUnitRuleReqIdentitiesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BatchCreateAuthUnitRuleReqIdentitiesInner is not found in the empty JSON string", BatchCreateAuthUnitRuleReqIdentitiesInner.openapiRequiredFields.toString()));
        }
      }


      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BatchCreateAuthUnitRuleReqIdentitiesInner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("identity_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `identity_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("identity_id").toString()));
      }
      if (!jsonObj.get("identity_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `identity_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("identity_type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BatchCreateAuthUnitRuleReqIdentitiesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BatchCreateAuthUnitRuleReqIdentitiesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BatchCreateAuthUnitRuleReqIdentitiesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BatchCreateAuthUnitRuleReqIdentitiesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<BatchCreateAuthUnitRuleReqIdentitiesInner>() {
           @Override
           public void write(JsonWriter out, BatchCreateAuthUnitRuleReqIdentitiesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BatchCreateAuthUnitRuleReqIdentitiesInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BatchCreateAuthUnitRuleReqIdentitiesInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BatchCreateAuthUnitRuleReqIdentitiesInner
  * @throws IOException if the JSON string is invalid with respect to BatchCreateAuthUnitRuleReqIdentitiesInner
  */
  public static BatchCreateAuthUnitRuleReqIdentitiesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BatchCreateAuthUnitRuleReqIdentitiesInner.class);
  }

 /**
  * Convert an instance of BatchCreateAuthUnitRuleReqIdentitiesInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

