/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;

import cn.idmesh.JSON;

/**
 * CreateAppReqConfigPropAllowedSocialLoginProvider
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreateAppReqConfigPropAllowedSocialLoginProvider {
  public static final String SERIALIZED_NAME_WECHAT_SCAN_QR = "wechat_scan_qr";
  @SerializedName(SERIALIZED_NAME_WECHAT_SCAN_QR)
  private Integer wechatScanQr;

  public static final String SERIALIZED_NAME_DINGDING_SCAN_QR = "dingding_scan_qr";
  @SerializedName(SERIALIZED_NAME_DINGDING_SCAN_QR)
  private Integer dingdingScanQr;

  public CreateAppReqConfigPropAllowedSocialLoginProvider() {
  }
   /**
   * Get wechatScanQr
   * @return wechatScanQr
  **/
  @javax.annotation.Nullable
  public Integer getWechatScanQr() {
    return wechatScanQr;
  }


  public void setWechatScanQr(Integer wechatScanQr) {
    this.wechatScanQr = wechatScanQr;
  }

   /**
   * Get dingdingScanQr
   * @return dingdingScanQr
  **/
  @javax.annotation.Nullable
  public Integer getDingdingScanQr() {
    return dingdingScanQr;
  }


  public void setDingdingScanQr(Integer dingdingScanQr) {
    this.dingdingScanQr = dingdingScanQr;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateAppReqConfigPropAllowedSocialLoginProvider createAppReqConfigPropAllowedSocialLoginProvider = (CreateAppReqConfigPropAllowedSocialLoginProvider) o;
    return Objects.equals(this.wechatScanQr, createAppReqConfigPropAllowedSocialLoginProvider.wechatScanQr) &&
        Objects.equals(this.dingdingScanQr, createAppReqConfigPropAllowedSocialLoginProvider.dingdingScanQr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wechatScanQr, dingdingScanQr);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAppReqConfigPropAllowedSocialLoginProvider {\n");
    sb.append("    wechatScanQr: ").append(toIndentedString(wechatScanQr)).append("\n");
    sb.append("    dingdingScanQr: ").append(toIndentedString(dingdingScanQr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("wechat_scan_qr");
    openapiFields.add("dingding_scan_qr");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CreateAppReqConfigPropAllowedSocialLoginProvider
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateAppReqConfigPropAllowedSocialLoginProvider.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateAppReqConfigPropAllowedSocialLoginProvider is not found in the empty JSON string", CreateAppReqConfigPropAllowedSocialLoginProvider.openapiRequiredFields.toString()));
        }
      }

        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateAppReqConfigPropAllowedSocialLoginProvider.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateAppReqConfigPropAllowedSocialLoginProvider' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateAppReqConfigPropAllowedSocialLoginProvider> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateAppReqConfigPropAllowedSocialLoginProvider.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateAppReqConfigPropAllowedSocialLoginProvider>() {
           @Override
           public void write(JsonWriter out, CreateAppReqConfigPropAllowedSocialLoginProvider value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateAppReqConfigPropAllowedSocialLoginProvider read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CreateAppReqConfigPropAllowedSocialLoginProvider given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CreateAppReqConfigPropAllowedSocialLoginProvider
  * @throws IOException if the JSON string is invalid with respect to CreateAppReqConfigPropAllowedSocialLoginProvider
  */
  public static CreateAppReqConfigPropAllowedSocialLoginProvider fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateAppReqConfigPropAllowedSocialLoginProvider.class);
  }

 /**
  * Convert an instance of CreateAppReqConfigPropAllowedSocialLoginProvider to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

