/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;

import cn.idmesh.JSON;

/**
 * 配置信息
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreateIDPConnectionReqConfigFields {
  public static final String SERIALIZED_NAME_CORP_ID = "CorpId";
  @SerializedName(SERIALIZED_NAME_CORP_ID)
  private String corpId;

  public static final String SERIALIZED_NAME_AGENT_ID = "AgentId";
  @SerializedName(SERIALIZED_NAME_AGENT_ID)
  private String agentId;

  public static final String SERIALIZED_NAME_CORP_SECRET = "CorpSecret";
  @SerializedName(SERIALIZED_NAME_CORP_SECRET)
  private String corpSecret;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public CreateIDPConnectionReqConfigFields() {
  }
   /**
   * Get corpId
   * @return corpId
  **/
  @javax.annotation.Nullable
  public String getCorpId() {
    return corpId;
  }


  public void setCorpId(String corpId) {
    this.corpId = corpId;
  }

   /**
   * Get agentId
   * @return agentId
  **/
  @javax.annotation.Nullable
  public String getAgentId() {
    return agentId;
  }


  public void setAgentId(String agentId) {
    this.agentId = agentId;
  }

   /**
   * Get corpSecret
   * @return corpSecret
  **/
  @javax.annotation.Nullable
  public String getCorpSecret() {
    return corpSecret;
  }


  public void setCorpSecret(String corpSecret) {
    this.corpSecret = corpSecret;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @javax.annotation.Nullable
  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateIDPConnectionReqConfigFields createIDPConnectionReqConfigFields = (CreateIDPConnectionReqConfigFields) o;
    return Objects.equals(this.corpId, createIDPConnectionReqConfigFields.corpId) &&
        Objects.equals(this.agentId, createIDPConnectionReqConfigFields.agentId) &&
        Objects.equals(this.corpSecret, createIDPConnectionReqConfigFields.corpSecret) &&
        Objects.equals(this.displayName, createIDPConnectionReqConfigFields.displayName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(corpId, agentId, corpSecret, displayName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateIDPConnectionReqConfigFields {\n");
    sb.append("    corpId: ").append(toIndentedString(corpId)).append("\n");
    sb.append("    agentId: ").append(toIndentedString(agentId)).append("\n");
    sb.append("    corpSecret: ").append(toIndentedString(corpSecret)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("CorpId");
    openapiFields.add("AgentId");
    openapiFields.add("CorpSecret");
    openapiFields.add("displayName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CreateIDPConnectionReqConfigFields
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateIDPConnectionReqConfigFields.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateIDPConnectionReqConfigFields is not found in the empty JSON string", CreateIDPConnectionReqConfigFields.openapiRequiredFields.toString()));
        }
      }

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("CorpId") != null && !jsonObj.get("CorpId").isJsonNull()) && !jsonObj.get("CorpId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `CorpId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("CorpId").toString()));
      }
      if ((jsonObj.get("AgentId") != null && !jsonObj.get("AgentId").isJsonNull()) && !jsonObj.get("AgentId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `AgentId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("AgentId").toString()));
      }
      if ((jsonObj.get("CorpSecret") != null && !jsonObj.get("CorpSecret").isJsonNull()) && !jsonObj.get("CorpSecret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `CorpSecret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("CorpSecret").toString()));
      }
      if ((jsonObj.get("displayName") != null && !jsonObj.get("displayName").isJsonNull()) && !jsonObj.get("displayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `displayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateIDPConnectionReqConfigFields.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateIDPConnectionReqConfigFields' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateIDPConnectionReqConfigFields> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateIDPConnectionReqConfigFields.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateIDPConnectionReqConfigFields>() {
           @Override
           public void write(JsonWriter out, CreateIDPConnectionReqConfigFields value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateIDPConnectionReqConfigFields read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CreateIDPConnectionReqConfigFields given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CreateIDPConnectionReqConfigFields
  * @throws IOException if the JSON string is invalid with respect to CreateIDPConnectionReqConfigFields
  */
  public static CreateIDPConnectionReqConfigFields fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateIDPConnectionReqConfigFields.class);
  }

 /**
  * Convert an instance of CreateIDPConnectionReqConfigFields to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

