/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cn.idmesh.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;

import cn.idmesh.JSON;

/**
 * ModifyAppProtocol
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ModifyAppProtocol {
  public static final String SERIALIZED_NAME_CONFIG_CONTENT = "config_content";
  @SerializedName(SERIALIZED_NAME_CONFIG_CONTENT)
  private Object configContent;

  public ModifyAppProtocol() {
  }
   /**
   * 配置参数
   * @return configContent
  **/
  @javax.annotation.Nullable
  public Object getConfigContent() {
    return configContent;
  }


  public void setConfigContent(Object configContent) {
    this.configContent = configContent;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifyAppProtocol modifyAppProtocol = (ModifyAppProtocol) o;
    return Objects.equals(this.configContent, modifyAppProtocol.configContent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configContent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyAppProtocol {\n");
    sb.append("    configContent: ").append(toIndentedString(configContent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("config_content");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ModifyAppProtocol
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ModifyAppProtocol.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ModifyAppProtocol is not found in the empty JSON string", ModifyAppProtocol.openapiRequiredFields.toString()));
        }
      }

        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ModifyAppProtocol.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ModifyAppProtocol' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ModifyAppProtocol> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ModifyAppProtocol.class));

       return (TypeAdapter<T>) new TypeAdapter<ModifyAppProtocol>() {
           @Override
           public void write(JsonWriter out, ModifyAppProtocol value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ModifyAppProtocol read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ModifyAppProtocol given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ModifyAppProtocol
  * @throws IOException if the JSON string is invalid with respect to ModifyAppProtocol
  */
  public static ModifyAppProtocol fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ModifyAppProtocol.class);
  }

 /**
  * Convert an instance of ModifyAppProtocol to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

