/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.idmesh.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.idmesh.model.CreateAppReqProtocolPropResponseAttrInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.idmesh.JSON;

/**
 * 默认 oidc 相关配置
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreateAppReqProtocolProp {
  public static final String SERIALIZED_NAME_ACS_URL = "acs_url";
  @SerializedName(SERIALIZED_NAME_ACS_URL)
  private String acsUrl;

  public static final String SERIALIZED_NAME_SP_ENTITY = "sp_entity";
  @SerializedName(SERIALIZED_NAME_SP_ENTITY)
  private String spEntity;

  public static final String SERIALIZED_NAME_RESPONSE_ATTR = "response_attr";
  @SerializedName(SERIALIZED_NAME_RESPONSE_ATTR)
  private List<CreateAppReqProtocolPropResponseAttrInner> responseAttr;

  public static final String SERIALIZED_NAME_DIGEST_ALGORITHM = "digest_algorithm";
  @SerializedName(SERIALIZED_NAME_DIGEST_ALGORITHM)
  private String digestAlgorithm;

  public static final String SERIALIZED_NAME_LIFETIME_IN_SECONDS = "lifetime_in_seconds";
  @SerializedName(SERIALIZED_NAME_LIFETIME_IN_SECONDS)
  private Integer lifetimeInSeconds;

  public static final String SERIALIZED_NAME_SIGNATURE_ALGORITHM = "signature_algorithm";
  @SerializedName(SERIALIZED_NAME_SIGNATURE_ALGORITHM)
  private String signatureAlgorithm;

  public static final String SERIALIZED_NAME_NAME_IDENTIFIER_FORMAT = "name_identifier_format";
  @SerializedName(SERIALIZED_NAME_NAME_IDENTIFIER_FORMAT)
  private String nameIdentifierFormat;

  public static final String SERIALIZED_NAME_AUTHN_CONTEXT_CLASS_REF = "authn_context_class_ref";
  @SerializedName(SERIALIZED_NAME_AUTHN_CONTEXT_CLASS_REF)
  private String authnContextClassRef;

  public static final String SERIALIZED_NAME_SAML_RESPONSE_SIGNING_KEY = "saml_response_signing_key";
  @SerializedName(SERIALIZED_NAME_SAML_RESPONSE_SIGNING_KEY)
  private String samlResponseSigningKey;

  public static final String SERIALIZED_NAME_SAML_RESPONSE_SIGNING_CERT = "saml_response_signing_cert";
  @SerializedName(SERIALIZED_NAME_SAML_RESPONSE_SIGNING_CERT)
  private String samlResponseSigningCert;

  public static final String SERIALIZED_NAME_SAML_RESPONSE_SIGNING_CERT_FINGERPRINT = "saml_response_signing_cert_fingerprint";
  @SerializedName(SERIALIZED_NAME_SAML_RESPONSE_SIGNING_CERT_FINGERPRINT)
  private String samlResponseSigningCertFingerprint;

  public CreateAppReqProtocolProp() {
  }
   /**
   * Get acsUrl
   * @return acsUrl
  **/
  @javax.annotation.Nullable
  public String getAcsUrl() {
    return acsUrl;
  }


  public void setAcsUrl(String acsUrl) {
    this.acsUrl = acsUrl;
  }

   /**
   * Get spEntity
   * @return spEntity
  **/
  @javax.annotation.Nullable
  public String getSpEntity() {
    return spEntity;
  }


  public void setSpEntity(String spEntity) {
    this.spEntity = spEntity;
  }

   /**
   * Get responseAttr
   * @return responseAttr
  **/
  @javax.annotation.Nullable
  public List<CreateAppReqProtocolPropResponseAttrInner> getResponseAttr() {
    return responseAttr;
  }


  public void setResponseAttr(List<CreateAppReqProtocolPropResponseAttrInner> responseAttr) {
    this.responseAttr = responseAttr;
  }

   /**
   * Get digestAlgorithm
   * @return digestAlgorithm
  **/
  @javax.annotation.Nullable
  public String getDigestAlgorithm() {
    return digestAlgorithm;
  }


  public void setDigestAlgorithm(String digestAlgorithm) {
    this.digestAlgorithm = digestAlgorithm;
  }

   /**
   * Get lifetimeInSeconds
   * @return lifetimeInSeconds
  **/
  @javax.annotation.Nullable
  public Integer getLifetimeInSeconds() {
    return lifetimeInSeconds;
  }


  public void setLifetimeInSeconds(Integer lifetimeInSeconds) {
    this.lifetimeInSeconds = lifetimeInSeconds;
  }

   /**
   * Get signatureAlgorithm
   * @return signatureAlgorithm
  **/
  @javax.annotation.Nullable
  public String getSignatureAlgorithm() {
    return signatureAlgorithm;
  }


  public void setSignatureAlgorithm(String signatureAlgorithm) {
    this.signatureAlgorithm = signatureAlgorithm;
  }

   /**
   * Get nameIdentifierFormat
   * @return nameIdentifierFormat
  **/
  @javax.annotation.Nullable
  public String getNameIdentifierFormat() {
    return nameIdentifierFormat;
  }


  public void setNameIdentifierFormat(String nameIdentifierFormat) {
    this.nameIdentifierFormat = nameIdentifierFormat;
  }

   /**
   * Get authnContextClassRef
   * @return authnContextClassRef
  **/
  @javax.annotation.Nullable
  public String getAuthnContextClassRef() {
    return authnContextClassRef;
  }


  public void setAuthnContextClassRef(String authnContextClassRef) {
    this.authnContextClassRef = authnContextClassRef;
  }

   /**
   * Get samlResponseSigningKey
   * @return samlResponseSigningKey
  **/
  @javax.annotation.Nullable
  public String getSamlResponseSigningKey() {
    return samlResponseSigningKey;
  }


  public void setSamlResponseSigningKey(String samlResponseSigningKey) {
    this.samlResponseSigningKey = samlResponseSigningKey;
  }

   /**
   * Get samlResponseSigningCert
   * @return samlResponseSigningCert
  **/
  @javax.annotation.Nullable
  public String getSamlResponseSigningCert() {
    return samlResponseSigningCert;
  }


  public void setSamlResponseSigningCert(String samlResponseSigningCert) {
    this.samlResponseSigningCert = samlResponseSigningCert;
  }

   /**
   * Get samlResponseSigningCertFingerprint
   * @return samlResponseSigningCertFingerprint
  **/
  @javax.annotation.Nullable
  public String getSamlResponseSigningCertFingerprint() {
    return samlResponseSigningCertFingerprint;
  }


  public void setSamlResponseSigningCertFingerprint(String samlResponseSigningCertFingerprint) {
    this.samlResponseSigningCertFingerprint = samlResponseSigningCertFingerprint;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateAppReqProtocolProp createAppReqProtocolProp = (CreateAppReqProtocolProp) o;
    return Objects.equals(this.acsUrl, createAppReqProtocolProp.acsUrl) &&
        Objects.equals(this.spEntity, createAppReqProtocolProp.spEntity) &&
        Objects.equals(this.responseAttr, createAppReqProtocolProp.responseAttr) &&
        Objects.equals(this.digestAlgorithm, createAppReqProtocolProp.digestAlgorithm) &&
        Objects.equals(this.lifetimeInSeconds, createAppReqProtocolProp.lifetimeInSeconds) &&
        Objects.equals(this.signatureAlgorithm, createAppReqProtocolProp.signatureAlgorithm) &&
        Objects.equals(this.nameIdentifierFormat, createAppReqProtocolProp.nameIdentifierFormat) &&
        Objects.equals(this.authnContextClassRef, createAppReqProtocolProp.authnContextClassRef) &&
        Objects.equals(this.samlResponseSigningKey, createAppReqProtocolProp.samlResponseSigningKey) &&
        Objects.equals(this.samlResponseSigningCert, createAppReqProtocolProp.samlResponseSigningCert) &&
        Objects.equals(this.samlResponseSigningCertFingerprint, createAppReqProtocolProp.samlResponseSigningCertFingerprint);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acsUrl, spEntity, responseAttr, digestAlgorithm, lifetimeInSeconds, signatureAlgorithm, nameIdentifierFormat, authnContextClassRef, samlResponseSigningKey, samlResponseSigningCert, samlResponseSigningCertFingerprint);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAppReqProtocolProp {\n");
    sb.append("    acsUrl: ").append(toIndentedString(acsUrl)).append("\n");
    sb.append("    spEntity: ").append(toIndentedString(spEntity)).append("\n");
    sb.append("    responseAttr: ").append(toIndentedString(responseAttr)).append("\n");
    sb.append("    digestAlgorithm: ").append(toIndentedString(digestAlgorithm)).append("\n");
    sb.append("    lifetimeInSeconds: ").append(toIndentedString(lifetimeInSeconds)).append("\n");
    sb.append("    signatureAlgorithm: ").append(toIndentedString(signatureAlgorithm)).append("\n");
    sb.append("    nameIdentifierFormat: ").append(toIndentedString(nameIdentifierFormat)).append("\n");
    sb.append("    authnContextClassRef: ").append(toIndentedString(authnContextClassRef)).append("\n");
    sb.append("    samlResponseSigningKey: ").append(toIndentedString(samlResponseSigningKey)).append("\n");
    sb.append("    samlResponseSigningCert: ").append(toIndentedString(samlResponseSigningCert)).append("\n");
    sb.append("    samlResponseSigningCertFingerprint: ").append(toIndentedString(samlResponseSigningCertFingerprint)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("acs_url");
    openapiFields.add("sp_entity");
    openapiFields.add("response_attr");
    openapiFields.add("digest_algorithm");
    openapiFields.add("lifetime_in_seconds");
    openapiFields.add("signature_algorithm");
    openapiFields.add("name_identifier_format");
    openapiFields.add("authn_context_class_ref");
    openapiFields.add("saml_response_signing_key");
    openapiFields.add("saml_response_signing_cert");
    openapiFields.add("saml_response_signing_cert_fingerprint");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CreateAppReqProtocolProp
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateAppReqProtocolProp.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateAppReqProtocolProp is not found in the empty JSON string", CreateAppReqProtocolProp.openapiRequiredFields.toString()));
        }
      }

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("acs_url") != null && !jsonObj.get("acs_url").isJsonNull()) && !jsonObj.get("acs_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `acs_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("acs_url").toString()));
      }
      if ((jsonObj.get("sp_entity") != null && !jsonObj.get("sp_entity").isJsonNull()) && !jsonObj.get("sp_entity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sp_entity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sp_entity").toString()));
      }
      if (jsonObj.get("response_attr") != null && !jsonObj.get("response_attr").isJsonNull()) {
        JsonArray jsonArrayresponseAttr = jsonObj.getAsJsonArray("response_attr");
        if (jsonArrayresponseAttr != null) {
          // ensure the json data is an array
          if (!jsonObj.get("response_attr").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `response_attr` to be an array in the JSON string but got `%s`", jsonObj.get("response_attr").toString()));
          }

          // validate the optional field `response_attr` (array)
          for (int i = 0; i < jsonArrayresponseAttr.size(); i++) {
            CreateAppReqProtocolPropResponseAttrInner.validateJsonElement(jsonArrayresponseAttr.get(i));
          };
        }
      }
      if ((jsonObj.get("digest_algorithm") != null && !jsonObj.get("digest_algorithm").isJsonNull()) && !jsonObj.get("digest_algorithm").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `digest_algorithm` to be a primitive type in the JSON string but got `%s`", jsonObj.get("digest_algorithm").toString()));
      }
      if ((jsonObj.get("signature_algorithm") != null && !jsonObj.get("signature_algorithm").isJsonNull()) && !jsonObj.get("signature_algorithm").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `signature_algorithm` to be a primitive type in the JSON string but got `%s`", jsonObj.get("signature_algorithm").toString()));
      }
      if ((jsonObj.get("name_identifier_format") != null && !jsonObj.get("name_identifier_format").isJsonNull()) && !jsonObj.get("name_identifier_format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name_identifier_format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name_identifier_format").toString()));
      }
      if ((jsonObj.get("authn_context_class_ref") != null && !jsonObj.get("authn_context_class_ref").isJsonNull()) && !jsonObj.get("authn_context_class_ref").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `authn_context_class_ref` to be a primitive type in the JSON string but got `%s`", jsonObj.get("authn_context_class_ref").toString()));
      }
      if ((jsonObj.get("saml_response_signing_key") != null && !jsonObj.get("saml_response_signing_key").isJsonNull()) && !jsonObj.get("saml_response_signing_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `saml_response_signing_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("saml_response_signing_key").toString()));
      }
      if ((jsonObj.get("saml_response_signing_cert") != null && !jsonObj.get("saml_response_signing_cert").isJsonNull()) && !jsonObj.get("saml_response_signing_cert").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `saml_response_signing_cert` to be a primitive type in the JSON string but got `%s`", jsonObj.get("saml_response_signing_cert").toString()));
      }
      if ((jsonObj.get("saml_response_signing_cert_fingerprint") != null && !jsonObj.get("saml_response_signing_cert_fingerprint").isJsonNull()) && !jsonObj.get("saml_response_signing_cert_fingerprint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `saml_response_signing_cert_fingerprint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("saml_response_signing_cert_fingerprint").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateAppReqProtocolProp.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateAppReqProtocolProp' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateAppReqProtocolProp> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateAppReqProtocolProp.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateAppReqProtocolProp>() {
           @Override
           public void write(JsonWriter out, CreateAppReqProtocolProp value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateAppReqProtocolProp read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CreateAppReqProtocolProp given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CreateAppReqProtocolProp
  * @throws IOException if the JSON string is invalid with respect to CreateAppReqProtocolProp
  */
  public static CreateAppReqProtocolProp fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateAppReqProtocolProp.class);
  }

 /**
  * Convert an instance of CreateAppReqProtocolProp to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

