/*
 * IDMesh-Dev
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.idmesh.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.idmesh.JSON;

/**
 * 配置信息
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DeleteIDPConnectionRetConfigFields {
  public static final String SERIALIZED_NAME_APP_ID = "AppId";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  private String appId;

  public static final String SERIALIZED_NAME_APP_SECRET = "AppSecret";
  @SerializedName(SERIALIZED_NAME_APP_SECRET)
  private String appSecret;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_CORP_ID = "CorpId";
  @SerializedName(SERIALIZED_NAME_CORP_ID)
  private String corpId;

  public static final String SERIALIZED_NAME_AGENT_ID = "AgentId";
  @SerializedName(SERIALIZED_NAME_AGENT_ID)
  private String agentId;

  public static final String SERIALIZED_NAME_CORP_SECRET = "CorpSecret";
  @SerializedName(SERIALIZED_NAME_CORP_SECRET)
  private String corpSecret;

  public DeleteIDPConnectionRetConfigFields() {
  }
   /**
   * Get appId
   * @return appId
  **/
  @javax.annotation.Nullable
  public String getAppId() {
    return appId;
  }


  public void setAppId(String appId) {
    this.appId = appId;
  }

   /**
   * Get appSecret
   * @return appSecret
  **/
  @javax.annotation.Nullable
  public String getAppSecret() {
    return appSecret;
  }


  public void setAppSecret(String appSecret) {
    this.appSecret = appSecret;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @javax.annotation.Nullable
  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

   /**
   * Get corpId
   * @return corpId
  **/
  @javax.annotation.Nullable
  public String getCorpId() {
    return corpId;
  }


  public void setCorpId(String corpId) {
    this.corpId = corpId;
  }

   /**
   * Get agentId
   * @return agentId
  **/
  @javax.annotation.Nullable
  public String getAgentId() {
    return agentId;
  }


  public void setAgentId(String agentId) {
    this.agentId = agentId;
  }

   /**
   * Get corpSecret
   * @return corpSecret
  **/
  @javax.annotation.Nullable
  public String getCorpSecret() {
    return corpSecret;
  }


  public void setCorpSecret(String corpSecret) {
    this.corpSecret = corpSecret;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteIDPConnectionRetConfigFields deleteIDPConnectionRetConfigFields = (DeleteIDPConnectionRetConfigFields) o;
    return Objects.equals(this.appId, deleteIDPConnectionRetConfigFields.appId) &&
        Objects.equals(this.appSecret, deleteIDPConnectionRetConfigFields.appSecret) &&
        Objects.equals(this.displayName, deleteIDPConnectionRetConfigFields.displayName) &&
        Objects.equals(this.corpId, deleteIDPConnectionRetConfigFields.corpId) &&
        Objects.equals(this.agentId, deleteIDPConnectionRetConfigFields.agentId) &&
        Objects.equals(this.corpSecret, deleteIDPConnectionRetConfigFields.corpSecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, appSecret, displayName, corpId, agentId, corpSecret);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteIDPConnectionRetConfigFields {\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    appSecret: ").append(toIndentedString(appSecret)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    corpId: ").append(toIndentedString(corpId)).append("\n");
    sb.append("    agentId: ").append(toIndentedString(agentId)).append("\n");
    sb.append("    corpSecret: ").append(toIndentedString(corpSecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("AppId");
    openapiFields.add("AppSecret");
    openapiFields.add("displayName");
    openapiFields.add("CorpId");
    openapiFields.add("AgentId");
    openapiFields.add("CorpSecret");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to DeleteIDPConnectionRetConfigFields
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DeleteIDPConnectionRetConfigFields.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DeleteIDPConnectionRetConfigFields is not found in the empty JSON string", DeleteIDPConnectionRetConfigFields.openapiRequiredFields.toString()));
        }
      }

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("AppId") != null && !jsonObj.get("AppId").isJsonNull()) && !jsonObj.get("AppId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `AppId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("AppId").toString()));
      }
      if ((jsonObj.get("AppSecret") != null && !jsonObj.get("AppSecret").isJsonNull()) && !jsonObj.get("AppSecret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `AppSecret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("AppSecret").toString()));
      }
      if ((jsonObj.get("displayName") != null && !jsonObj.get("displayName").isJsonNull()) && !jsonObj.get("displayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `displayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayName").toString()));
      }
      if ((jsonObj.get("CorpId") != null && !jsonObj.get("CorpId").isJsonNull()) && !jsonObj.get("CorpId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `CorpId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("CorpId").toString()));
      }
      if ((jsonObj.get("AgentId") != null && !jsonObj.get("AgentId").isJsonNull()) && !jsonObj.get("AgentId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `AgentId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("AgentId").toString()));
      }
      if ((jsonObj.get("CorpSecret") != null && !jsonObj.get("CorpSecret").isJsonNull()) && !jsonObj.get("CorpSecret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `CorpSecret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("CorpSecret").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeleteIDPConnectionRetConfigFields.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeleteIDPConnectionRetConfigFields' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeleteIDPConnectionRetConfigFields> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeleteIDPConnectionRetConfigFields.class));

       return (TypeAdapter<T>) new TypeAdapter<DeleteIDPConnectionRetConfigFields>() {
           @Override
           public void write(JsonWriter out, DeleteIDPConnectionRetConfigFields value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DeleteIDPConnectionRetConfigFields read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DeleteIDPConnectionRetConfigFields given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DeleteIDPConnectionRetConfigFields
  * @throws IOException if the JSON string is invalid with respect to DeleteIDPConnectionRetConfigFields
  */
  public static DeleteIDPConnectionRetConfigFields fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeleteIDPConnectionRetConfigFields.class);
  }

 /**
  * Convert an instance of DeleteIDPConnectionRetConfigFields to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

